rm -rf frameworks/base/package/overlays/NavigationBarModeGesturalOverlay
rm -rf frameworks/base/package/overlays/NavigationBarModeGesturalOverlayWideBack
rm -rf frameworks/base/package/overlays/NavigationBarModeGesturalOverlayNarrowBack
rm -rf frameworks/base/package/overlays/NavigationBarModeGesturalOverlayExtraWideBack
